### ISSUE TITLE
자바의 main 메서드는 왜 항상 public static이여야 할까요?

### ISSUE THREAD

**Issue by shkisme** [Java-Spring-Study/java-spring-study#1]
자바 프로그래밍을 할 때 `main`을 치면 자동완성 되는 main 함수는 항상 `public static`입니다. 
어느 새인가 아무 생각 없이 사용하고 있는데, 왜 반드시 `static` 함수이여야 하는지 한번 정리해보고 싶습니다.

**Comment by shkisme** [comment]
static 메서드들 사이에 호출되는 순서?
https://it-mesung.tistory.com/86

**Comment by fienestar** [comment]
참조하신 사이트를 보면 `static 변수 및 블록은 선언되어 있는 순서대로 실행된다.`라 되어있습니다.
static method와 변수, 블록을 착각하신 것 같습니다. static method 는 사용자가 직접 호출하지 않는 이상 실행되지 않으며 그저 함수일 뿐인것으로 알고 있습니다. 단지 main은 entry point이기 때문에 처음에 예외적으로 실행될 뿐이죠

**Comment by shkisme** [comment]
와 그렇군요!! 감사합니다. 모르고 있던 부분을 알아갑니다!👍
