### ISSUE TITLE
Application run failed 에러를 해결하고 싶습니다.

### ISSUE THREAD

**Issue by chagieun** [Java-Spring-Study/java-spring-study#4]
HelloSpringApplication.java를 run하였을 때  
ERROR 17544 --- [           main] o.s.boot.SpringApplication               : Application run failed
이러한 에러 메세지가 뜹니다. 어떻게하면 해결할 수 있을까요?
![ApplicationRunFailed](https://user-images.githubusercontent.com/90942759/191888572-7f1c4426-c981-4786-beb9-036d52949cbc.JPG)

**Comment by shkisme** [comment]
엇 이건 어떤 부분 때문에 발생하는 문제일까요...? 스터디때 화면공유 한번 해주셔서 같이 해결해봅시다
